appName: Shovels

servers:
  - name: default
    uri: amqp://guest:guest@127.0.01/%2F
    apiPort: 15672

    ikue:
      appName: ~
      component: ~

  - name: default
    uri: amqp://guest:guest@127.0.01/%2F
    apiPort: 15672

    ikue:
      appName: ~
      component: ~

shovels:
  - name: default
    src:
      worker_id: event_name
      server: default

    dest:
      worker_id: event_name2
      server: default
